/**
 * Các hằng số định nghĩa action type cho habits
 */
export enum HabitActionTypes {
  // Fetch Habits
  FETCH_HABITS_REQUEST = 'FETCH_HABITS_REQUEST',
  FETCH_HABITS_SUCCESS = 'FETCH_HABITS_SUCCESS',
  FETCH_HABITS_FAILURE = 'FETCH_HABITS_FAILURE',
  
  // Create Habit
  CREATE_HABIT_REQUEST = 'CREATE_HABIT_REQUEST',
  CREATE_HABIT_SUCCESS = 'CREATE_HABIT_SUCCESS',
  CREATE_HABIT_FAILURE = 'CREATE_HABIT_FAILURE',
  
  // Update Habit
  UPDATE_HABIT_REQUEST = 'UPDATE_HABIT_REQUEST',
  UPDATE_HABIT_SUCCESS = 'UPDATE_HABIT_SUCCESS',
  UPDATE_HABIT_FAILURE = 'UPDATE_HABIT_FAILURE',
  
  // Delete Habit
  DELETE_HABIT_REQUEST = 'DELETE_HABIT_REQUEST',
  DELETE_HABIT_SUCCESS = 'DELETE_HABIT_SUCCESS',
  DELETE_HABIT_FAILURE = 'DELETE_HABIT_FAILURE',
  
  // Complete Habit
  COMPLETE_HABIT_REQUEST = 'COMPLETE_HABIT_REQUEST',
  COMPLETE_HABIT_SUCCESS = 'COMPLETE_HABIT_SUCCESS',
  COMPLETE_HABIT_FAILURE = 'COMPLETE_HABIT_FAILURE',
  
  // Habit Completions
  FETCH_COMPLETIONS_REQUEST = 'FETCH_COMPLETIONS_REQUEST',
  FETCH_COMPLETIONS_SUCCESS = 'FETCH_COMPLETIONS_SUCCESS',
  FETCH_COMPLETIONS_FAILURE = 'FETCH_COMPLETIONS_FAILURE',
  
  // Habit Statistics
  FETCH_HABIT_STATS_REQUEST = 'FETCH_HABIT_STATS_REQUEST',
  FETCH_HABIT_STATS_SUCCESS = 'FETCH_HABIT_STATS_SUCCESS',
  FETCH_HABIT_STATS_FAILURE = 'FETCH_HABIT_STATS_FAILURE',
  
  // UI Actions
  SELECT_HABIT = 'SELECT_HABIT',
  FILTER_HABITS = 'FILTER_HABITS',
  SORT_HABITS = 'SORT_HABITS',
  
  // Reminder Actions
  ADD_REMINDER = 'ADD_REMINDER',
  UPDATE_REMINDER = 'UPDATE_REMINDER',
  DELETE_REMINDER = 'DELETE_REMINDER',
} 